# Generated by Django 6.0.1 on 2026-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartVest", "0003_filterpreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="filterpreset",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="filterpreset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
