# Generated by Django 6.0.1 on 2026-02-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartVest", "0005_watchedunicorn"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacktestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("profile_type", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("initial_capital", models.FloatField(default=10000.0)),
                ("rebalance_months", models.IntegerField(default=3)),
                ("total_return", models.FloatField(blank=True, null=True)),
                ("cagr", models.FloatField(blank=True, null=True)),
                ("sharpe_ratio", models.FloatField(blank=True, null=True)),
                ("sortino_ratio", models.FloatField(blank=True, null=True)),
                ("max_drawdown", models.FloatField(blank=True, null=True)),
                ("max_drawdown_duration", models.IntegerField(blank=True, null=True)),
                ("calmar_ratio", models.FloatField(blank=True, null=True)),
                ("annual_volatility", models.FloatField(blank=True, null=True)),
                ("alpha", models.FloatField(blank=True, null=True)),
                ("beta", models.FloatField(blank=True, null=True)),
                ("benchmark_return", models.FloatField(blank=True, null=True)),
                ("outperformance", models.FloatField(blank=True, null=True)),
                ("final_value", models.FloatField(blank=True, null=True)),
                ("n_trading_days", models.IntegerField(blank=True, null=True)),
                ("n_rebalances", models.IntegerField(default=0)),
                ("n_stocks_avg", models.FloatField(blank=True, null=True)),
                ("equity_curve_json", models.JSONField(blank=True, default=dict)),
                ("benchmark_curve_json", models.JSONField(blank=True, default=dict)),
                ("snapshots_json", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
